// <auto-generated />
using System;
using BoilerMonitorWeb.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoilerMonitorWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626093950_AddIdentityTables")]
    partial class AddIdentityTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoilerMonitorWeb.Application.Domain.Entities.AlarmDefinition", b =>
                {
                    b.Property<int>("AlarmDefID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlarmDefID"));

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlarmDefID");

                    b.ToTable("AlarmDefinitions", "dbo");
                });

            modelBuilder.Entity("BoilerMonitorWeb.Application.Domain.Entities.AlarmLog", b =>
                {
                    b.Property<long>("AlarmID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AlarmID"));

                    b.Property<int?>("AckBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AckTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("bit");

                    b.Property<int>("AlarmDefID")
                        .HasColumnType("int");

                    b.Property<int>("BoilerID")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AlarmID");

                    b.ToTable("AlarmLogs", "dbo");
                });

            modelBuilder.Entity("BoilerMonitorWeb.Application.Domain.Entities.Boiler", b =>
                {
                    b.Property<int>("BoilerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoilerID"));

                    b.Property<decimal?>("Capacity_KGHR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BoilerID");

                    b.ToTable("Boilers", "dbo");
                });

            modelBuilder.Entity("BoilerMonitorWeb.Application.Domain.Entities.Telemetry", b =>
                {
                    b.Property<int>("BoilerID")
                        .HasColumnType("int");

                    b.Property<decimal>("FeedwaterTemp_C")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FlueGasTemp_C")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LogTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("O2_Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SteamFlow_KGHR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SteamPressure_Bar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SteamTemp_C")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WaterLevel_mm")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("BoilerLogs", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
